# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Appointment Title')),
                ('description', models.TextField(verbose_name='Appointment Description')),
                ('info', models.TextField(blank=True, verbose_name='Aditional Info')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'verbose_name': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Appointment_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField(verbose_name='Appointment Date')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='appointments.Appointment', verbose_name='appointment')),
            ],
            options={
                'verbose_name_plural': 'Appointment Dates',
                'verbose_name': 'Appointment Date',
            },
        ),
        migrations.CreateModel(
            name='Appointment_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Appointment Start Time')),
                ('end_time', models.TimeField(verbose_name='Appointment End Time')),
                ('app_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='appointments.Appointment_Date', verbose_name='dates')),
            ],
            options={
                'verbose_name_plural': 'Appointment Times',
                'verbose_name': 'Appointment Time',
            },
        ),
    ]
