# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Appointment Description'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Aditional Info'),
        ),
    ]
