# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appoointmentapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppoointmentApplication',
            new_name='AppointmentApplication',
        ),
    ]
