# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20170418_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentApplication',
            new_name='Appointment_Application',
        ),
    ]
